apiVersion: v1
kind: Namespace
metadata:
  name: emqx
---
# Headless service for EMQX clustering (used for DNS discovery)
apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: emqx
spec:
  clusterIP: None
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
    - name: dashboard
      port: 18083
---
# NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
  namespace: emqx
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 30083
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31083
---
# StatefulSet for EMQX cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: emqx
spec:
  serviceName: emqx-headless
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:5.3.0
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8883
              name: ssl
            - containerPort: 18083
              name: dashboard
          env:
            - name: EMQX_CLUSTER__DISCOVERY
              value: "k8s"
            - name: EMQX_K8S__NAMESPACE
              value: "emqx"
            - name: EMQX_K8S__APP_NAME
              value: "emqx"
            - name: EMQX_NODE__COOKIE
              value: "secretcookie"
            - name: EMQX_NODE__NAME
              value: "emqx@$(POD_NAME)"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 10
      terminationGracePeriodSeconds: 30
