# StatefulSet for EMQX cluster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: emqx
spec:
  serviceName: emqx-headless
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:5.3.0
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8883
              name: ssl
            - containerPort: 18083
              name: dashboard
          env:
            # Cluster discovery using Kubernetes DNS
            - name: EMQX_CLUSTER__DISCOVERY
              value: "k8s"
            - name: EMQX_K8S__NAMESPACE
              value: "emqx"
            - name: EMQX_K8S__APP_NAME
              value: "emqx"
            # Same cookie for all nodes
            - name: EMQX_NODE__COOKIE
              value: "secretcookie"
            # Node name template must include pod name for clustering
            - name: EMQX_NODE__NAME
              value: "emqx@$(EMQX_POD_NAME)"
            - name: EMQX_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
      terminationGracePeriodSeconds: 30
