apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx-cluster
  namespace: emqx
spec:
  # --------------------------
  #       EMQX VERSION
  # --------------------------
  image: emqx:5.7.1

  # --------------------------
  #       CLUSTER MODE
  # --------------------------
  bootstrapConfig:
    emqx:
      cluster:
        discovery: "k8s"
        k8s:
          apiserver: https://kubernetes.default.svc
          namespaceSelector: emqx
          serviceSelector: emqx-cluster-headless

  # --------------------------
  #   REPLICAS (CLUSTER SIZE)
  # --------------------------
  coreTemplate:
    spec:
      replicas: 3

      # Enable persistence for StatefulSet
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: standard   # For Minikube/Kind
          resources:
            requests:
              storage: 5Gi

  # --------------------------
  #      EXPOSE SERVICES
  # --------------------------
  listenersServiceTemplate:
    metadata:
      name: emqx-service
    spec:
      type: LoadBalancer
      ports:
      - name: mqtt
        port: 1883
        targetPort: 1883
      - name: dashboard
        port: 18083
        targetPort: 18083
