apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  type: LoadBalancer       # equal round-robin LB
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: dashboard
      port: 18083
      targetPort: 18083
