apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx/emqx:5.7.1

  coreTemplate:
    spec:
      replicas: 3
      podLabels:
        app: emqx-core

  bootstrapConfig: |
    node {
      cookie = "emqxsecretcookie"
    }
