apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: emqx
spec:
  serviceName: "emqx-headless"
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:5.3.0
          ports:
            - containerPort: 1883   # MQTT
            - containerPort: 18083  # Dashboard
          env:
            - name: EMQX_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EMQX_CLUSTER__DISCOVERY
              value: "k8s"
            - name: EMQX_K8S__NAMESPACE
              value: "emqx"
            - name: EMQX_NODE__COOKIE
              value: "secretcookie"
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
  namespace: emqx
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 30083
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31083
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: emqx
spec:
  clusterIP: None
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
    - name: dashboard
      port: 18083
