apiVersion: v1
kind: Namespace
metadata:
  name: emqx
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
  namespace: emqx
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 30083  # accessible from host
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 31083  # accessible from host
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: emqx
spec:
  serviceName: emqx-service
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:5.3.0
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 18083
              name: dashboard
          env:
            - name: EMQX_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EMQX_CLUSTER__DISCOVERY
              value: "k8s"
          readinessProbe:
            httpGet:
              path: /status
              port: 18083
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 20
            periodSeconds: 10
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
