apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx
  namespace: emqx
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emqx
  namespace: emqx
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emqx
  namespace: emqx
subjects:
- kind: ServiceAccount
  name: emqx
  namespace: emqx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emqx
