version: "3.8"

services:
  timp-mysql:
    image: mysql:8.0
    container_name: timp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timpdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  timp-backend:
    image: sanchaljustgrow/timp-frontend:TIMP-API-0.0.1-SNAPSHOT
    container_name: timp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://timp-mysql:3306/timpdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - timp-mysql
    ports:
      - "8081:8080"
    restart: always

  timp-frontend:
    image: sanchaljustgrow/timp-frontend:TIMP2.0.0
    container_name: timp-frontend
    ports:
      - "8082:80"
    environment:
      - apiUrl = http://localhost:8081/v1
    depends_on:
      - timp-backend
    restart: always

volumes:
  mysql_data:
